# Generated by Django 4.2.7 on 2025-11-29 15:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0002_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='cor_cabelo',
            field=models.CharField(default='', max_length=50, verbose_name='Cor do Cabelo'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cor_linha',
            field=models.CharField(default='', max_length=50, verbose_name='Cor da Linha'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='estado_cabelo',
            field=models.CharField(choices=[('novo', 'Novo'), ('descolorido', 'Descolorido'), ('branco', 'Branco'), ('preto', 'Preto'), ('castanho', 'Castanho'), ('rubro', 'Rubro'), ('loiro', 'Loiro'), ('pintado', 'Pintado')], default='novo', max_length=20, verbose_name='Estado do Cabelo'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='peso_gramas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (em gramas)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='ordens_servico.servico', verbose_name='Serviço'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tamanho_cabelo_cm',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tamanho do Cabelo (cm)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_cabelo',
            field=models.CharField(choices=[('liso', 'Liso'), ('ondulado', 'Ondulado'), ('cacheado', 'Cacheado'), ('crespo', 'Crespo')], default='liso', max_length=20, verbose_name='Tipo de Cabelo'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_metro',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor em reais por metro', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor por Metro (R$)'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
