# Generated by Django 4.2.7 on 2025-11-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0003_ordemservico_cor_cabelo_ordemservico_cor_linha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_faturamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Faturamento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='faturada',
            field=models.BooleanField(default=False, verbose_name='Faturada'),
        ),
    ]
