# Generated by Django 4.2.7 on 2025-12-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0004_ordemservico_data_faturamento_ordemservico_faturada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='entregue',
            field=models.BooleanField(default=False, verbose_name='Entregue'),
        ),
    ]
