# Generated by Django 4.2.7 on 2025-12-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0005_ordemservico_entregue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='foto_entrega',
            field=models.ImageField(blank=True, help_text='Foto comprovando a entrega da ordem de serviço', null=True, upload_to='fotos_entrega/', verbose_name='Foto da Entrega'),
        ),
    ]
