# Generated by Django 4.2.7 on 2025-12-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0006_ordemservico_foto_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='pago_na_entrega',
            field=models.BooleanField(default=False, help_text='Indica se a OS já foi paga na entrega', verbose_name='Pago na Entrega'),
        ),
    ]
