# Generated by Django 4.2.7 on 2025-12-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0007_ordemservico_pago_na_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito')], help_text='Forma de pagamento utilizada na OS', max_length=20, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
