# Generated by Django 4.2.7 on 2026-01-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0008_ordemservico_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorCabelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cor do Cabelo',
                'verbose_name_plural': 'Cores do Cabelo',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CorLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cor da Linha',
                'verbose_name_plural': 'Cores da Linha',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCabelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(help_text='Valor usado no banco (ex: novo, descolorido)', max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estado do Cabelo',
                'verbose_name_plural': 'Estados do Cabelo',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoCabelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(help_text='Valor usado no banco (ex: liso, ondulado)', max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cabelo',
                'verbose_name_plural': 'Tipos de Cabelo',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
