# Generated by Django 4.2.7 on 2026-01-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0009_corcabelo_corlinha_estadocabelo_tipocabelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
