# Generated by Django 4.2.7 on 2026-01-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0010_alter_cliente_cnpj_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='eh_parceiro',
            field=models.BooleanField(default=False, help_text='Indica se o cliente tem vínculo de parceiro (pode deixar pendurado na conta)', verbose_name='É Parceiro'),
        ),
    ]
