# Generated by Django 4.2.7 on 2026-04-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0011_add_eh_parceiro_to_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='prazo_entrega',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='ItemOrdemServico',
        ),
    ]
