# Generated by Django 4.2.7 on 2026-04-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0012_alter_ordemservico_prazo_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
    ]
