# Generated by Django 4.2.7 on 2026-09-12 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0016_add_valor_recebido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='custo_cabelo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quanto a Barra pagou pelo cabelo quando a origem é própria', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo do cabelo (R$)'),
        ),
        # OS que já existem entram com False (podem "informar depois");
        # a partir daqui toda OS nova nasce exigindo o peso final.
        migrations.AddField(
            model_name='ordemservico',
            name='exige_peso_final',
            field=models.BooleanField(default=False, help_text='Falso nas OS criadas antes do controle de perdas (podem informar depois)', verbose_name='Exige peso final ao finalizar'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='exige_peso_final',
            field=models.BooleanField(default=True, help_text='Falso nas OS criadas antes do controle de perdas (podem informar depois)', verbose_name='Exige peso final ao finalizar'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='limpeza_mesclagem',
            field=models.BooleanField(default=False, help_text='Com limpeza/mesclagem a perda esperada é de até 40% (sem, 20%)', verbose_name='Limpeza/mesclagem autorizada'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='origem_cabelo',
            field=models.CharField(choices=[('cliente', 'Da cliente'), ('proprio', 'Nosso')], default='cliente', max_length=10, verbose_name='Origem do cabelo'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='peso_final_gramas',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Peso final (g)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tamanho_final_cm',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tamanho final (cm)'),
        ),
    ]
