# Generated by Django 4.2.7 on 2026-09-13 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordens_servico', '0017_controle_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlteracaoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('corrigir_pagamento', 'Pagamento corrigido'), ('estornar_faturamento', 'Faturamento estornado'), ('cancelar_faturada', 'OS faturada cancelada')], max_length=30)),
                ('motivo', models.TextField()),
                ('dados_antes', models.JSONField(default=dict)),
                ('dados_depois', models.JSONField(default=dict)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracoes', to='ordens_servico.ordemservico')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_os', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alteração de OS',
                'verbose_name_plural': 'Alterações de OS',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
