# Generated by Django 4.2.7 on 2026-09-13 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordens_servico', '0018_historico_alteracoes_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='finalizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_finalizadas_por', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado por'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='inicio_trabalho',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início do trabalho'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='responsavel',
            field=models.ForeignKey(blank=True, help_text='Funcionário que assumiu a OS ao movê-la para Em Desenvolvimento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
