# Generated by Django 4.2.7 on 2026-04-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_saidacaixa_tipo_criado_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saidacaixa',
            options={'ordering': ['-data', '-data_criacao'], 'verbose_name': 'Lançamento de Caixa', 'verbose_name_plural': 'Lançamentos de Caixa'},
        ),
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='saidacaixa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
