# Generated by Django 4.2.7 on 2026-09-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0004_configuracaoempresa_pin_faturamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidacaixa',
            name='tipo_material',
            field=models.CharField(blank=True, choices=[('linha', 'Linha'), ('cola', 'Cola'), ('tela', 'Tela'), ('fita_silicone', 'Fita/silicone'), ('embalagem', 'Embalagem'), ('compra_cabelo', 'Compra de cabelo'), ('outro', 'Outro')], default='', max_length=20, verbose_name='Tipo de material'),
        ),
    ]
